title: WiscoSAC
description: Community updates and resources
url: https://wiscosac.github.io
baseurl: ""
theme: null
markdown: kramdown
permalink: /:categories/:title/

# Treat folders as “collections” so files render and can be auto-listed
collections:
  meetings:
    output: true
    permalink: /meetings/:name/
  projects:
    output: true
    permalink: /projects/:name/
  resources:
    output: true
    permalink: /resources/:name/
  workshops:
    output: true
    permalink: /workshops/:name/

# So Jekyll recognizes them even though they aren't under _collections
defaults:
  - scope: { path: "meetings" }
    values: { layout: page, collection: meetings }
  - scope: { path: "projects" }
    values: { layout: page, collection: projects }
  - scope: { path: "workshops" }
    values: { layout: page, collection: workshops }
  - scope: { path: "resources" }
    values: { layout: page, collection: resources }

# GitHub Pages-safe plugins (enable if you use Actions build)
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 10
paginate_path: "/page:num"
